#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Routines for working with ``mwTab`` format files used by the 
Metabolomics Workbench.

This package includes the following modules:

``mwtab``
    This module provides the :class:`~mwtab.mwtab.MWTabFile` class which is a python
    dictionary representation of a Metabolomics Workbench `mwtab` file. Data can be accessed
    directly from the :class:`~mwtab.mwtab.MWTabFile` instance using bracket accessors.

``cli``
    This module provides command-line interface for the ``mwtab`` package.

``tokenizer``
    This module provides the :func:`~mwtab.tokenizer.tokenizer` generator that generates
    tuples of key-value pairs from `mwtab` files.

``fileio``
    This module provides the :func:`~mwtab.fileio.read_files` generator
    to open files from different sources (single file/multiple files on a local 
    machine, directory/archive of files, URL address of a file).

``converter``
    This module provides the :class:`~mwtab.converter.Converter` class that is
    responsible for the conversion of ``mwTab`` formated files into their JSON
    representation and vice versa.

``mwschema``
    This module provides JSON schema definitions for the ``mwTab`` formatted files,
    i.e. specifies required and optional keys as well as data types.

``validator``
    This module provides routines to validate ``mwTab`` formatted files based
    on schema definitions as well as checks for file self-consistency.

``mwrest``
    This module provides the :class:`~mwtab.mwrest.GenericMWURL` class which is a
    python dictionary representation of a Metabolomics Workbench REST URL. The class
    is used to validate query parameters and to generate a URL path which can be
    used to request data from Metabolomics Workbench through their REST API.
    
``metadata_column_matching``
    This module provides the :class:`~mwtab.metadata_column_matching.ColumnFinder` class 
    which is composed of a :class:`~mwtab.metadata_column_matching.NameMatcher` and 
    :class:`~mwtab.metadata_column_matching.ValueMatcher`. They are used to match 
    column names and values, respecitively. Matching is done using regular expressions 
    the "in" operator, equality operator, and type matching for values. This module 
    also includes the "column_finders" dicitonary which is a dictionary of ColumnFinders 
    created to match the most common columns found in the Metabolomics Workbench datasets. 
    More information about this module can be found on the :doc:`metadata_column_matching` page.
"""
from logging import getLogger, NullHandler
from .fileio import read_files, read_mwrest
from .validator import validate_file
from .mwrest import GenericMWURL

# __version__ = "1.2.5.post1"


# Setting default logging handler
getLogger(__name__).addHandler(NullHandler())


try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import version as __version__
except ImportError:
    # -- Source mode --
    # use setuptools_scm to get the current version from src using git
    from setuptools_scm import get_version as _gv
    from os import path as _path
    __version__ = _gv(_path.join(_path.dirname(__file__), _path.pardir))


