# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.2.6.dev7+g1244622.d20240411'
__version_tuple__ = version_tuple = (1, 2, 6, 'dev7', 'g1244622.d20240411')
