language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - python -m pytest -v --cov=./mwtab
#generate code coverage report
after_success:
  - codecov