language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# command to run tests
jobs:
  include:
    - stage: test
      dist: xenial
      python: "3.5"
      script:
        - python -m pytest -v --cov=./mwtab
    - stage: test
      dist: bionic
      python: "3.6"
      script:
        - python -m pytest -v --cov=./mwtab
    - stage: test
      dist: bionic
      python: "3.7"
      script:
        - python -m pytest -v --cov=./mwtab
    - stage: test
      dist: bionic
      python: "3.8"
      script:
        - python -m pytest -v --cov=./mwtab
    - stage: test
      dist: bionic
      python: "3.9"
      script:
        - python -m pytest -v --cov=./mwtab
#generate code coverage report
after_success:
  - codecov
